/** Compile static centroid data into independently compiled, per-category C sources. */
import {existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseArgs} from 'node:util';
import {gunzipSync} from 'node:zlib';

import {sha256} from '../evaluation/codebase-data.ts';
import {inspectNativeContents} from '../native.ts';

import {verifyCodebaseRelease} from './codebase-release.ts';
import {compareIds} from './spatial.ts';

interface NativePoint {
    id: string;
    category: string;
    observations: string;
    vector: number[];
    description: string
}

interface NativeTable {
    points: NativePoint[];
    categories: string[];
    dimensions: number;
    releaseSha256: string;
    categoryMetadata?: {name: string; description : string}[]|undefined
}

const marker = '/* Curated static knowledge baseline; maintain these C sources directly. */';
const legacyMarker = '/* Generated by compile-native-knowledge.ts; do not edit by hand. */';
const {values} = parseArgs({
    options : {
        release : {type : 'string'},
        'source-c' : {type : 'string'},
        output : {type : 'string'},
        'top-per-category' : {type : 'string'}
    }
});
if ((!values.release && !values['source-c']) || (values.release && values['source-c']) ||
    !values.output)
    throw new Error(
        'Usage: --release <verified-release> | --source-c <table.c> --output <table.c> [--top-per-category <count>]');

function cString(value: string) {
    if (!/^[a-zA-Z0-9_:/.-]+$/.test(value))
        throw new Error(`Unsupported native identifier: ${value}`);
    return `"${value}"`;
}

function hasCompilerMarker(source: string) {
    return source.startsWith(marker) || source.startsWith(legacyMarker);
}

function loadRelease(directory: string): NativeTable {
    const verified = verifyCodebaseRelease(directory);
    const points = verified.index.points.map(point => ({
                                                 id : point.id,
                                                 category : point.category,
                                                 observations : point.observations,
                                                 vector : point.vector,
                                                 description : ''
                                             }));
    return {
        points,
        categories : [...new Set(points.map(point => point.category)) ].sort(compareIds),
        dimensions : verified.index.dimensions,
        releaseSha256 : sha256(readFileSync(resolve(directory, 'manifest.json')))
    };
}

/** Read generated C sources, including legacy monolithic tables and include fragments. */
function loadGeneratedC(path: string): NativeTable {
    const source = readFileSync(path, 'utf8');
    if (!hasCompilerMarker(source))
        throw new Error('Source C file is not generated by compile-native-knowledge.ts');
    const categoryBlock =
        source.match(/const char \*const cgai_static_knowledge_categories\[\] = \{([\s\S]*?)\n\};/);
    const rowBlock = source.match(
        /const cgai_static_knowledge_centroid cgai_static_knowledge_data\[\] = \{([\s\S]*?)\n\};/);
    const dimensions = source.match(
        /(?:cgai_knowledge_catalog_dimensions|cgai_static_knowledge_dimensions) = (\d+)U;/);
    const releaseSha = source.match(
        /(?:cgai_knowledge_catalog_release_sha256|cgai_static_knowledge_release_sha256_value)\[\] = "([a-f0-9]{64}|)";/);
    if (!dimensions || !releaseSha)
        throw new Error('Generated C table is missing required metadata');
    const categoryKeys = new Map<number, string>();
    const includes = [
        ...source.matchAll(
            /#include "(?:static_knowledge_data|knowledge_catalog)\/((?:category-\d+|\d+-[a-z0-9-]+)\.inc)"/g)
    ].map(match => match[1]!);
    const categorySources = [
        ...source.matchAll(
            /\/\* Category source: (?:static_knowledge_data|knowledge_catalog)\/(\d+-[a-z0-9-]+\.c) \*\//g)
    ].map(match => match[1]!);
    const files = categorySources.length ? categorySources : includes;
    const contents = files.map(name => {
        for (const directory of ['knowledge_catalog', 'static_knowledge_data']) {
            const candidate = resolve(dirname(path), directory, name);
            if (existsSync(candidate))
                return readFileSync(candidate, 'utf8');
        }
        throw new Error(`Missing generated knowledge category source: ${name}`);
    });
    const moduleMetadata = categoryBlock ? undefined : contents.map(text => {
        function field(name: string) {
            const match = text.match(new RegExp(`\\.${name} = "((?:[^"\\\\]|\\\\.)*)"`));
            if (!match)
                throw new Error(`Missing module metadata: ${name}`);
            return JSON.parse(`"${match[1]}"`) as string;
        }
        // Module metadata follows the private centroid array.
        const module = text.slice(text.indexOf('static const cgai_knowledge_module module'));
        text = module;
        return {key : field('key'), name : field('name'), description : field('description')};
    });
    const categoryLabels =
        categoryBlock ? [...categoryBlock[1]!.matchAll(/"([a-zA-Z0-9_:/.,&() -]+)"/g) ].map(
                            match => match[1]!)
                      : moduleMetadata!.map(item => item.name);
    if (!categoryLabels.length || categoryLabels.some(label => !label.trim()))
        throw new Error('Generated C table has invalid category labels');
    const rows = files.length ? contents.join('\n') : rowBlock?.[1] ?? '';
    if (!rowBlock && !files.length)
        throw new Error('Generated C table has no centroid rows or category sources');
    const points: NativePoint[] = [];
    const sharedBlock = source.match(
        /const float (?:cgai_knowledge_catalog_vectors|cgai_shared_knowledge_vectors)\[\]\[CGAI_STATIC_KNOWLEDGE_DIMENSIONS\] = \{([\s\S]*?)\n\};/);
    const sharedVectors =
        sharedBlock ? [...sharedBlock[1]!.matchAll(/\{([^{}]+)\}/g) ].map(match => match[1]!) : [];
    const rowPattern =
        /\{\s*(?:\.id\s*=\s*)?"([a-zA-Z0-9_:/.-]+)",\s*(?:\.category\s*=\s*)?(\d+)U,\s*(?:\.observations\s*=\s*)?UINT64_C\((\d+)\),\s*(?:(?:\.description\s*=\s*)?"((?:[^"\\]|\\.)*)",\s*)?(?:\.cluster\s*=\s*\d+U,\s*)?(?:\.vector\s*=\s*)?(?:(?:\(const float\[CGAI_STATIC_KNOWLEDGE_DIMENSIONS\]\))?\{([^{}]+)\}|(?:cgai_knowledge_catalog_vectors|cgai_shared_knowledge_vectors)\[\s*(\d+)\s*\])\s*\},?/g;
    for (const row of rows.matchAll(rowPattern)) {
        const categoryIndex = Number(row[2]);
        const category = moduleMetadata?.[categoryIndex]?.key ?? categoryKeyFromId(row[1]!);
        if (categoryIndex >= categoryLabels.length ||
            (categoryKeys.has(categoryIndex) && categoryKeys.get(categoryIndex) !== category))
            throw new Error(`Generated C table category mismatch: ${row[1]}`);
        categoryKeys.set(categoryIndex, category);
        const vectorText = row[5] ?? sharedVectors[Number(row[6])];
        if (!vectorText)
            throw new Error(`Missing shared vector: ${row[1]}`);
        // C baseline vectors use sparse designated initializers; omitted axes are zero.
        const literals = vectorText.replace(/\/\*[\s\S]*?\*\//g, '').split(',')
                             .map(value => value.trim()).filter(Boolean);
        const vector: number[] = [];
        let component = 0;
        for (const literal of literals) {
            const entry = literal.match(/^(?:\[\s*(\d+)\s*\]\s*=\s*)?([-+0-9.eE]+)F$/);
            if (!entry)
                throw new Error(`Invalid generated float literal: ${literal}`);
            if (entry[1] !== undefined)
                component = Number(entry[1]);
            if (component >= Number(dimensions[1]) || vector[component] !== undefined)
                throw new Error(`Invalid vector component: ${literal}`);
            vector[component++] = Number(entry[2]);
        }
        for (let component = 0; component < Number(dimensions[1]); ++component)
            vector[component] ??= 0;
        if (!category || vector.length !== Number(dimensions[1]) || !vector.every(Number.isFinite))
            throw new Error(`Invalid generated centroid row: ${row[1]}`);
        const description = row[4] === undefined ? '' : JSON.parse(`"${row[4]}"`) as string;
        points.push({id : row[1]!, category, observations : row[3]!, vector, description});
    }
    const count = source.match(
        /(?:cgai_knowledge_catalog_row_count|cgai_static_knowledge_data_count) = (\d+)U;/);
    if (!count || points.length !== Number(count[1]))
        throw new Error('Generated C table row count mismatch');
    const categories = categoryLabels.map((_, index) => {
        const key = categoryKeys.get(index);
        if (!key)
            throw new Error(`Generated C category ${index} has no centroid rows`);
        if (moduleMetadata && key !== moduleMetadata[index]!.key)
            throw new Error(`Generated C module key mismatch: ${index}`);
        return key;
    });
    const descriptionBlock = source.match(
        /const char \*const cgai_static_knowledge_category_descriptions\[\] = \{([\s\S]*?)\n\};/);
    const descriptions = descriptionBlock
                             ? [...descriptionBlock[1]!.matchAll(/"((?:[^"\\]|\\.)*)"/g) ].map(
                                   match => JSON.parse(`"${match[1]}"`) as string)
                             : moduleMetadata?.map(item => item.description);
    if (descriptions && descriptions.length !== categories.length)
        throw new Error('Generated C table category description count mismatch');
    points.sort((left, right) => compareIds(left.id, right.id));
    return {
        points,
        categories,
        dimensions : Number(dimensions[1]),
        releaseSha256 : releaseSha[1]!,
        categoryMetadata :
            descriptions
                ? categoryLabels.map((name, index) => ({name, description : descriptions[index]!}))
                : undefined
    };
}

function categoryKeyFromId(id: string) {
    // Maintained baseline IDs belong to a category, not an external model shard.
    const baseline = id.match(/^([a-z0-9/-]+):baseline-\d{3,}$/);
    if (baseline)
        return baseline[1]!;
    if (id.startsWith('encyclopedia:')) {
        const shard = id.slice('encyclopedia:'.length).split(':')[0]!;
        const cluster = shard.match(/^(cluster-\d+)-\d{4}$/)?.[1];
        if (!cluster)
            throw new Error(`Cannot recover encyclopedia category from ID: ${id}`);
        return `encyclopedia/${cluster}`;
    }
    const shard = id.split(':')[0]!;
    const category = shard.match(/^(.+)-\d{3}$/)?.[1];
    if (!category)
        throw new Error(`Cannot recover codebase category from ID: ${id}`);
    return category;
}

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..');
const commonTokens = new Set([
    'a',        'about',   'after',   'also',  'an',     'and',     'are',        'as',
    'at',       'be',      'because', 'been',  'before', 'between', 'but',        'by',
    'can',      'could',   'did',     'do',    'does',   'during',  'each',       'first',
    'for',      'from',    'had',     'has',   'have',   'he',      'her',        'here',
    'hers',     'him',     'his',     'how',   'if',     'in',      'into',       'is',
    'it',       'its',     'itself',  'just',  'many',   'may',     'might',      'more',
    'most',     'much',    'must',    'new',   'no',     'not',     'now',        'of',
    'off',      'often',   'on',      'once',  'one',    'only',    'or',         'other',
    'our',      'out',     'over',    'same',  'she',    'should',  'so',         'some',
    'such',     'than',    'that',    'the',   'their',  'them',    'themselves', 'then',
    'there',    'these',   'they',    'this',  'those',  'through', 'to',         'too',
    'under',    'until',   'up',      'us',    'very',   'was',     'we',         'were',
    'what',     'when',    'where',   'which', 'while',  'who',     'whom',       'why',
    'will',     'with',    'would',   'you',   'your',   'yours',   'january',    'february',
    'march',    'april',   'may',     'june',  'july',   'august',  'september',  'october',
    'november', 'december'
]);
const genericTopicTerms = new Set([
    'list', 'disambiguation', 'you', 'your', 'get', 'back', 'high', 'young', 'great', 'world',
    'national', 'international', 'group', 'division', 'season', 'common', 'special'
]);

function tokenExamples(items: {token: string; count : string}[]) {
    return items
        .filter(item => /^[a-z][a-z0-9'-]*$/i.test(item.token) &&
                        !commonTokens.has(item.token.toLowerCase()))
        .slice(0, 4)
        .map(item => `${item.token[0]!.toUpperCase()}${item.token.slice(1)} (${item.count})`);
}

function addEncyclopediaLabels(targets: Map<string, string[]>, topics: Map<string, string[]>) {
    const directory = resolve(repositoryRoot, 'knowledge/encyclopedia/simplewiki-v1');
    const sources = JSON.parse(readFileSync(resolve(directory, 'sources.json'), 'utf8')) as
                    {clusters : {id : string; title_terms : string[]}[]};
    const models =
        JSON.parse(readFileSync(resolve(directory, 'models.json'), 'utf8')) as
        {shards : {id : string; cluster : string; inspection : {path : string; sha256 : string}}[]};
    for (const cluster of sources.clusters) {
        const cues = cluster.title_terms.filter(term => !genericTopicTerms.has(term.toLowerCase()));
        topics.set(cluster.id, cues.slice(0, 6));
    }
    for (const shard of models.shards) {
        const bytes = readFileSync(resolve(directory, shard.inspection.path));
        if (sha256(bytes) !== shard.inspection.sha256)
            throw new Error(`Encyclopedia inspection checksum mismatch: ${shard.id}`);
        const inspection =
            JSON.parse(bytes.toString('utf8')) as
            {centroids : {id : number; tokens : {items : {token : string; count : string}[]}}[]};
        for (const centroid of inspection.centroids) {
            const id = `encyclopedia:${shard.id}:${String(centroid.id).padStart(4, '0')}`;
            targets.set(id, tokenExamples(centroid.tokens.items));
        }
    }
}

function addCodebaseLabels(targets: Map<string, string[]>) {
    const directory = resolve(repositoryRoot, 'knowledge/codebase/codebase-v1');
    const manifestPath = resolve(directory, 'manifest.json');
    if (!existsSync(manifestPath))
        return;
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
        files: {path: string; sha256 : string}[];
        shards: {id: string; model : string; centroids : number}[]
    };
    for (const shard of manifest.shards) {
        const compressed = readFileSync(resolve(directory, shard.model));
        const expected = manifest.files.find(file => file.path === shard.model);
        if (!expected || sha256(compressed) !== expected.sha256)
            throw new Error(`Codebase model checksum mismatch: ${shard.id}`);
        const payload = gunzipSync(compressed, {maxOutputLength : 64 * 1024 * 1024});
        for (let centroid = 0; centroid < shard.centroids; centroid++) {
            const detail = inspectNativeContents(payload, 'centroid', 0, 12, centroid);
            targets.set(`${shard.id}:${String(centroid).padStart(4, '0')}`,
                        tokenExamples(detail.tokens.items));
        }
    }
}

function describeCategories(categories: string[], topics: Map<string, string[]>) {
    const codebaseDescriptions: Record < string, {
        name: string;
        description: string
    }
    > = {
        build : {
            name : 'Build and Configuration',
            description : 'Build systems, compiler settings, and project configuration'
        },
        database : {
            name : 'Database and Persistence',
            description : 'Database schemas, migrations, and data access'
        },
        documentation : {
            name : 'Guides and Documentation',
            description : 'Project guides, API contracts, and technical documentation'
        },
        'native-bridge' : {
            name : 'Native Language Bridge',
            description : 'JavaScript to native C bindings and data conversion'
        },
        'native-core' : {
            name : 'Native C Core',
            description : 'Centroid-GAI C model, training, inference, and serialization'
        },
        'native-tests' :
            {name : 'Native C Tests', description : 'Native C tests and correctness fixtures'},
        'public-api' : {
            name : 'Public C API',
            description : 'Public C headers and supported library interfaces'
        },
        service : {
            name : 'Application Service',
            description : 'Persistence API, service logic, and shared application code'
        },
        tooling : {
            name : 'Developer and Knowledge Tools',
            description : 'Knowledge builders, evaluation, and repository tools'
        },
        // Historical snapshots still use this category; keep their generated metadata stable.
        web : {name : 'Web Application', description : 'Browser interface and web application code'}
    };
    return categories.map(category => {
        if (category.startsWith('encyclopedia/')) {
            const cluster = category.slice('encyclopedia/'.length);
            const words = topics.get(cluster) ?? [];
            const lower = new Set(words.map(word => word.toLowerCase()));
            const families = [
                {
                    name : 'Film, Television, and Comics',
                    words : [
                        'movie', 'film', 'actor', 'comics', 'episodes', 'television', 'spongebob'
                    ]
                },
                {
                    name : 'Music and Performing Arts',
                    words : [
                        'music', 'singer', 'orchestra', 'musician', 'rock', 'song', 'album', 'band'
                    ]
                },
                {
                    name : 'Video Games and Fantasy',
                    words : [ 'game', 'video', 'mario', 'fantasy', 'games', 'characters' ]
                },
                {
                    name : 'Geography, Nature, and Places',
                    words : [
                        'sea', 'lake', 'park', 'mount', 'storm', 'tropical', 'island', 'province',
                        'district', 'river', 'city', 'county'
                    ]
                },
                {
                    name : 'History, Government, and Conflict',
                    words : [
                        'war', 'battle', 'history', 'kingdom', 'republic', 'congress', 'state',
                        'election', 'presidential', 'politician', 'party', 'assembly'
                    ]
                },
                {
                    name : 'Education and Institutions',
                    words : [ 'university', 'college', 'academy', 'department', 'school' ]
                },
                {
                    name : 'Sports and Competitions',
                    words : [
                        'hockey', 'baseball', 'football', 'footballer', 'league', 'team',
                        'championship', 'olympics', 'cup'
                    ]
                },
                {
                    name : 'Science and Mathematics',
                    words : [
                        'mathematics', 'theory', 'computer', 'chemistry', 'reaction', 'tree',
                        'frog', 'language'
                    ]
                },
                {
                    name : 'Religion and Architecture',
                    words : [ 'church', 'cathedral', 'castle', 'shrine', 'temple' ]
                },
                {
                    name : 'People and Biographies',
                    words : [
                        'man', 'woman', 'biography', 'born', 'writer', 'peter', 'joseph', 'robert',
                        'michael', 'david'
                    ]
                }
            ];
            const family =
                families
                    .map(item =>
                             ({...item, score : item.words.filter(word => lower.has(word)).length}))
                    .sort((left, right) => right.score - left.score)[0];
            const cues = words.length
                             ? words.map(word => word[0]!.toUpperCase() + word.slice(1)).join(', ')
                             : 'A range of reference subjects';
            const familyName =
                family && family.score > 0 ? family.name : 'Mixed Encyclopedia Subjects';
            const name = `${familyName}: ${cues.split(', ').slice(0, 3).join(', ')}`;
            return {name, description : `${familyName}; article-title cues include ${cues}`};
        }
        return codebaseDescriptions[category] ?? {
            name : category.replaceAll('-', ' ').replace(/\b\w/g, letter => letter.toUpperCase()),
            description : `Repository material about ${category.replaceAll('-', ' ')}`
        };
    });
}

const table = values.release ? loadRelease(resolve(values.release))
                             : loadGeneratedC(resolve(values['source-c']!));
if (values['top-per-category'] !== undefined) {
    const limit = Number(values['top-per-category']);
    if (!Number.isSafeInteger(limit) || limit < 1)
        throw new Error('--top-per-category must be a positive safe integer');
    const grouped = new Map<string, NativePoint[]>();
    for (const point of table.points) {
        const group = grouped.get(point.category) ?? [];
        group.push(point);
        grouped.set(point.category, group);
    }
    table.points = [...grouped.values() ]
                       .flatMap(group => group
                                             .toSorted((left, right) => {
                                                 const leftCount = BigInt(left.observations);
                                                 const rightCount = BigInt(right.observations);
                                                 return leftCount > rightCount ? -1
                                                        : leftCount < rightCount
                                                            ? 1
                                                            : compareIds(left.id, right.id);
                                             })
                                             .slice(0, limit))
                       .sort((left, right) => compareIds(left.id, right.id));
}
const {points, categories, dimensions} = table;
if (points.length > 4096 || points.length * dimensions > 1048576 || categories.length > 64)
    throw new Error('Static knowledge exceeds native spatial index limits');
if (dimensions !== 32)
    throw new Error('Native knowledge compiler currently requires 32 dimensions');
for (let i = 0; i < points.length; i++) {
    const point = points[i]!;
    cString(point.id);
    cString(point.category);
    if (i > 0 && compareIds(points[i - 1]!.id, point.id) >= 0)
        throw new Error('Centroid IDs must be unique and sorted');
    if (!point.vector.every(Number.isFinite) || !/^\d+$/.test(point.observations))
        throw new Error(`Invalid centroid data: ${point.id}`);
    if (BigInt(point.observations) > 0xffffffffffffffffn)
        throw new Error(`Observation count exceeds uint64: ${point.id}`);
}
const targets = new Map<string, string[]>();
const encyclopediaTopics = new Map<string, string[]>();
if (!table.categoryMetadata) {
    addEncyclopediaLabels(targets, encyclopediaTopics);
    addCodebaseLabels(targets);
}
const categoryMetadata =
    table.categoryMetadata ?? describeCategories(categories, encyclopediaTopics);
const categoryNameById =
    new Map(categories.map((category, index) => [category, categoryMetadata[index]!.name]));
const categoryDescriptionById =
    new Map(categories.map((category, index) => [category, categoryMetadata[index]!.description]));
for (const point of points) {
    if (table.categoryMetadata && point.description)
        continue;
    const categoryDescription = categoryDescriptionById.get(point.category);
    if (!categoryDescription)
        throw new Error(`Missing readable category description: ${point.category}`);
    const examples = targets.get(point.id) ?? [];
    point.description =
        examples.length
            ? `${categoryDescription}; observed target words include ${examples.join(', ')}`
            : categoryDescription;
}

const manualFeatures = [
    'configuration', 'schema', 'read', 'write', 'validation', 'memory', 'numeric',
    'serialization'
];

function cFloat(value: number) {
    const literal = table.releaseSha256 === '' ? String(value) : value.toPrecision(9);
    return `${/[.eE]/.test(literal) ? literal : `${literal}.0`}F`;
}

const categoryIds = new Map(categories.map((category, index) => [category, index]));
const categoryGroups = new Map<string, NativePoint[]>();
for (const point of points) {
    const group = categoryGroups.get(point.category) ?? [];
    group.push(point);
    categoryGroups.set(point.category, group);
}
const outputDirectory = dirname(resolve(values.output));
const output = resolve(values.output);
const categoryDirectory = resolve(outputDirectory, 'knowledge_catalog');
// Deduplicate exact float32 coordinates, normalizing signed zero. Never merge nearby vectors.
const clusters = new Map < string, {
    index: number;
    vector: number[];
    members: number;
    observations: bigint;
    shared?: number
}
>();
const clusterById = new Map<string, number>();
for (const point of points) {
    const vector = point.vector.map(value => Math.fround(value) || 0);
    const key = JSON.stringify(vector);
    let cluster = clusters.get(key);
    if (!cluster) {
        cluster = {index : clusters.size, vector, members : 0, observations : 0n};
        clusters.set(key, cluster);
    }
    cluster.members++;
    cluster.observations += BigInt(point.observations);
    if (cluster.observations > 0xffffffffffffffffn)
        throw new Error(`Cluster observation count exceeds uint64: ${point.id}`);
    clusterById.set(point.id, cluster.index);
}
const clusterList = [...clusters.values() ];
const shared = clusterList.filter(cluster => cluster.members > 1);
shared.forEach((cluster, index) => { cluster.shared = index; });
const rowReferences = new Map < string, {
    category: number;
    row: number
}
>();
const categoryFiles = categories.map((category, index) => {
    const members = categoryGroups.get(category)!;
    const readableName = categoryNameById.get(category)!;
    const slug = readableName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const suffix = String(index).padStart(2, '0');
    const name = `${suffix}-${slug}.c`;
    const symbol = `cgai_knowledge_${category.replace(/[^a-z0-9]+/g, '_')}`;
    const lines = [
        marker,
        `/* Category: ${readableName}; centroids: ${members.length}. */`,
        '#include "../knowledge_catalog.h"',
        '',
        '/* Immutable search records, sorted by ID. Coordinates rank squared Euclidean',
        ' * distance. See docs/architecture.md for catalog context and feature axes. */',
        'static const cgai_static_knowledge_centroid centroids[] = {',
        ...members.flatMap((point, row) => {
            rowReferences.set(point.id, {category : index, row});
            const cluster = clusterList[clusterById.get(point.id)!]!;
            const vector = cluster.vector.map(cFloat);
            const categoryId = categoryIds.get(point.category);
            return [
                '    {',
                `        .id = ${cString(point.id)},`,
                `        .category = ${categoryId}U,`,
                `        .observations = UINT64_C(${point.observations}),`,
                `        .description = ${JSON.stringify(point.description)},`,
                `        .cluster = ${cluster.index}U,`,
                ...(cluster.shared !== undefined ? [`        .vector = cgai_knowledge_catalog_vectors[${cluster.shared}]`] : [
                '        .vector = (const float[CGAI_STATIC_KNOWLEDGE_DIMENSIONS]){',
                ...(table.releaseSha256 === '' ? vector.flatMap((value, axis) =>
                    cluster.vector[axis] === 0 && (axis !== 0 || cluster.vector.some(value => value !== 0)) ? [] :
                    [`            [${axis} /* ${manualFeatures[axis] ?? 'reserved'} */] = ${value},`]) : Array.from({length: Math.ceil(vector.length / 4)}, (_, offset) =>
                    `            ${vector.slice(offset * 4, offset * 4 + 4).join(', ')}${offset * 4 + 4 < vector.length ? ',' : ''}`)),
                '        }']), '    },'
            ];
        }),
        '};',
        '',
        'static const cgai_knowledge_module module = {',
        '    .category = {',
        `        .index = ${index}U,`,
        `        .key = ${cString(category)},`,
        `        .name = ${JSON.stringify(readableName)},`,
        `        .description = ${JSON.stringify(categoryDescriptionById.get(category))},`,
        '        .count = sizeof(centroids) / sizeof(centroids[0])',
        '    },',
        '    .rows = centroids',
        '};',
        '',
        '/** Return borrowed category metadata and rows, valid for the process lifetime.',
        ' * No allocation, file access, database query, or vector search occurs here. */',
        `const cgai_knowledge_module *${symbol}(void) {`,
        '    return &module;',
        '}',
        ''
    ];
    return {name, symbol, count : members.length, source : lines.join('\n')};
});
const header = [
    marker, '#ifndef CGAI_KNOWLEDGE_CATALOG_H', '#define CGAI_KNOWLEDGE_CATALOG_H', '',
    '#include "internal/knowledge_module.h"', '',
    ...(shared.length ? ['extern const float cgai_knowledge_catalog_vectors[][CGAI_STATIC_KNOWLEDGE_DIMENSIONS];', ''] : []),
    ...categoryFiles.map(file =>
        `const cgai_knowledge_module *${file.symbol}(void);`), '', '#endif', ''
].join('\n');
// Compress consecutive global rows into spans while retaining arbitrary category interleaving.
const spans: {first: number; count : number; category : number; local : number}[] = [];
points.forEach((point, first) => {
    const reference = rowReferences.get(point.id)!;
    const last = spans.at(-1);
    if (last && last.category === reference.category && last.local + last.count === reference.row)
        last.count++;
    else
        spans.push({first, count : 1, category : reference.category, local : reference.row});
});
const source = [
    marker, '#include "knowledge_catalog.h"', '',
    ...(shared.length ? ['const float cgai_knowledge_catalog_vectors[][CGAI_STATIC_KNOWLEDGE_DIMENSIONS] = {',
        ...shared.map(cluster => `    {${cluster.vector.map(cFloat).join(', ')}},`), '};', ''] : []),
    'const cgai_knowledge_provider cgai_knowledge_catalog_modules[] = {',
    ...categoryFiles.map(file => `    ${file.symbol},`), '};',
    `const size_t cgai_knowledge_catalog_category_count = ${categories.length}U;`, '',
    ...categoryFiles.map(file => `/* Category source: knowledge_catalog/${file.name} */`), '',
    'const cgai_knowledge_span cgai_knowledge_catalog_spans[] = {',
    ...spans.map(span => `    {${span.first}U, ${span.count}U, ${span.category}U, ${span.local}U},`), '};',
    `const size_t cgai_knowledge_catalog_span_count = ${spans.length}U;`,
    `const size_t cgai_knowledge_catalog_row_count = ${points.length}U;`,
    `const size_t cgai_knowledge_catalog_cluster_count = ${clusters.size}U;`,
    `const size_t cgai_knowledge_catalog_dimensions = ${dimensions}U;`,
    `const char cgai_knowledge_catalog_release_sha256[] = ${JSON.stringify(table.releaseSha256)};`, ''
].join('\n');

const existingOutput = existsSync(output) ? readFileSync(output, 'utf8') : undefined;
if (existingOutput !== undefined && !hasCompilerMarker(existingOutput))
    throw new Error('Refusing to overwrite a non-generated C file');
const headerPath = resolve(outputDirectory, 'knowledge_catalog.h');
if (existsSync(headerPath) && !hasCompilerMarker(readFileSync(headerPath, 'utf8')))
    throw new Error('Refusing to overwrite a non-generated header');
mkdirSync(categoryDirectory, {recursive : true});
const existingFiles =
    readdirSync(categoryDirectory)
        .filter(name => /^(?:category-\d+|\d+-[a-z0-9-]+)\.(?:inc|c)$/.test(name));
for (const name of existingFiles) {
    if (!hasCompilerMarker(readFileSync(resolve(categoryDirectory, name), 'utf8')))
        throw new Error(`Refusing to overwrite non-generated category file: ${name}`);
}
for (const file of categoryFiles)
    writeFileSync(resolve(categoryDirectory, file.name), file.source);
for (const name of existingFiles) {
    if (!categoryFiles.some(file => file.name === name))
        unlinkSync(resolve(categoryDirectory, name));
}
writeFileSync(headerPath, header);
writeFileSync(output, source);
console.log(JSON.stringify({
    output,
    points : points.length,
    categories : categories.length,
    sources : categoryFiles.length
}));
