/** Authored question families. Anchors must still match exactly when rebuilding candidates. */
export interface RepositorySeed {
    id: string;
    split: 'train' | 'development' | 'test';
    domain: 'build' | 'native' | 'persistence' | 'training' | 'evidence';
    path: string;
    topic: string;
    anchor: string;
    question: string;
    followup: string;
    correction: string;
    unavailable: string;
}

export const repositorySeeds: readonly RepositorySeed[] = [
    { id: 'cmake-minimum', split: 'train', domain: 'build', path: 'CMakeLists.txt', topic: 'CMake requirements',
        anchor: 'cmake_minimum_required(VERSION 3.20)', question: 'Which CMake line declares the minimum supported version?',
        followup: 'What minimum version does that declaration require?', correction: 'I mean the CMake minimum, rather than the compiler version.',
        unavailable: 'Which exact CMake version is installed on our production host right now?' },
    { id: 'c-standard', split: 'train', domain: 'build', path: 'CMakeLists.txt', topic: 'the C language standard',
        anchor: 'set(CMAKE_C_STANDARD 11)', question: 'Which C standard does the root build configure?',
        followup: 'Which numeric language standard is selected there?', correction: 'Please check the configured C language level, rather than a C++ level.',
        unavailable: 'Did the last production build actually compile every target using that C standard?' },
    { id: 'tests-default', split: 'train', domain: 'build', path: 'CMakeLists.txt', topic: 'the CMake test option',
        anchor: 'option(CGAI_BUILD_TESTS "Build the test suite" ON)', question: 'Which build option controls tests and what is its default?',
        followup: 'Is the test suite enabled in that option declaration?', correction: 'I mean the default test build option, not the result of a test run.',
        unavailable: 'Two operators disagree about whether our deployed binary was built with tests; which is correct?' },
    { id: 'docs-default', split: 'train', domain: 'build', path: 'CMakeLists.txt', topic: 'the documentation build option',
        anchor: 'option(CGAI_BUILD_DOCS "Build API documentation with Doxygen" OFF)', question: 'How does the root CMake file configure documentation generation by default?',
        followup: 'Which Doxygen build option is off there?', correction: 'Check documentation generation, rather than test generation.',
        unavailable: 'Where is the latest generated production documentation currently hosted?' },
    { id: 'sanitizers-default', split: 'train', domain: 'build', path: 'CMakeLists.txt', topic: 'the sanitizer build option',
        anchor: 'option(CGAI_ENABLE_SANITIZERS "Enable AddressSanitizer and UndefinedBehaviorSanitizer" OFF)', question: 'Which CMake option enables address and undefined-behavior sanitizers?',
        followup: 'What default does that sanitizer option declare?', correction: 'I mean the sanitizer option itself, not a compiler warning flag.',
        unavailable: 'Has the production deployment had zero sanitizer findings this month?' },
    { id: 'build-requirements', split: 'train', domain: 'build', path: 'docs/development.md', topic: 'native build requirements',
        anchor: 'Requirements: CMake 3.20 or newer and an ISO C11 compiler.', question: 'Which CMake version and compiler does the development guide require?',
        followup: 'What tool versions does that native build requirement specify?', correction: 'I meant native build requirements rather than Node service requirements.',
        unavailable: 'What exact compiler version is installed on our production build server?' },
    { id: 'build-command', split: 'train', domain: 'build', path: 'docs/development.md', topic: 'compiling the native release build',
        anchor: 'cmake --build build/dev --config Release', question: 'Which documented command builds the configured native release target?',
        followup: 'How does the guide invoke the build for that configuration?', correction: 'I meant the compilation command, not CMake configuration.',
        unavailable: 'One teammate says the release build passed and another says it failed; which run result is verified?' },
    { id: 'ctest-command', split: 'train', domain: 'build', path: 'docs/development.md', topic: 'the full native test command',
        anchor: 'ctest --test-dir build/dev -C Release --output-on-failure', question: 'What command does the development guide use for the native release tests?',
        followup: 'Which CTest command prints failing output for that build?', correction: 'Use the full native suite command rather than the neural-only filter.',
        unavailable: 'Did the entire native release suite pass on my machine today?' },
    { id: 'no-api-url', split: 'train', domain: 'persistence', path: 'docs/development.md', topic: 'API test preconditions',
        anchor: 'A skipped suite is not an API pass.',
        question: 'Can skipped API tests be counted as a successful API run?', followup: 'Does a skipped suite establish an API pass?',
        correction: 'I mean a missing API URL and skipped tests, rather than successful API execution.',
        unavailable: 'Which API endpoint is reachable from our CI runner at this moment?' },
    { id: 'function-budgets', split: 'train', domain: 'native', path: 'docs/development.md', topic: 'native function complexity budgets',
        anchor: 'The configured function budgets are 20 statements, eight branches and seven\nparameters.',
        question: 'Which statement, branch and parameter budgets are documented for C functions?', followup: 'What are those three configured function budgets?',
        correction: 'I meant function complexity budgets, not a memory allocation budget.',
        unavailable: 'Which function in my uncommitted changes currently violates the complexity budgets?' },
    { id: 'chat-protocol', split: 'train', domain: 'native', path: 'include/centroid_gai_chat.h', topic: 'the chat protocol version',
        anchor: '#define CGAI_CHAT_PROTOCOL_VERSION 2U', question: 'Which chat protocol version is declared in the public header?',
        followup: 'What value does that protocol macro expose?', correction: 'I mean the chat protocol version rather than the tokenizer version.',
        unavailable: 'Two deployed servers report different protocol versions; which server handled my last request?' },
    { id: 'chat-tokenizer', split: 'train', domain: 'native', path: 'include/centroid_gai_chat.h', topic: 'the chat tokenizer version',
        anchor: '#define CGAI_CHAT_TOKENIZER_VERSION 1U', question: 'What tokenizer version does the chat header declare?',
        followup: 'Which value is assigned to that tokenizer macro?', correction: 'Please inspect the tokenizer version, not the artifact protocol number.',
        unavailable: 'Has our production deployment reindexed every document for its current tokenizer?' },
    { id: 'artifact-limit', split: 'train', domain: 'native', path: 'include/centroid_gai_chat.h', topic: 'the chat artifact byte limit',
        anchor: '#define CGAI_CHAT_MAX_ARTIFACT_BYTES 67108864U', question: 'Which macro declares the maximum encoded chat artifact size?',
        followup: 'What byte bound does that artifact macro specify?', correction: 'I mean the artifact byte limit, not the vocabulary size.',
        unavailable: 'How many bytes does the newest production artifact currently occupy?' },
    { id: 'chat-default-shape', split: 'train', domain: 'training', path: 'include/centroid_gai_chat.h', topic: 'the default chat window shape',
        anchor: '/** @brief Return a reproducible shape with 160 prompt, 32 response and 80 evidence slots.',
        question: 'Which default prompt, response and evidence slot counts are documented?', followup: 'What are the three default slot counts for that shape?',
        correction: 'I meant the default chat windows, not the dimensions of token embeddings.',
        unavailable: 'What prompt and evidence windows did an operator choose for our unpublished production model?' },
    { id: 'chat-frozen-vocab', split: 'train', domain: 'training', path: 'include/centroid_gai_chat.h', topic: 'chat vocabulary construction',
        anchor: '/** @brief Initialize all weights and build vocabulary only from the supplied training split.',
        question: 'Which split does the public chat contract use when building vocabulary?', followup: 'May held-out examples supply vocabulary to that initialization step?',
        correction: 'Check vocabulary construction during initialization rather than generation.',
        unavailable: 'Was an externally supplied checkpoint secretly trained on our held-out test questions?' },
    { id: 'worker-shutdown', split: 'train', domain: 'persistence', path: 'persistence/api/src/chat/workers.ts', topic: 'worker admission during shutdown',
        anchor: "if (this.closed) return Promise.reject(new ChatWorkerError('chat workers are shutting down', 503));",
        question: 'How does worker admission reject requests after shutdown begins?',
        followup: 'Which status accompanies that shutting-down rejection?', correction: 'Inspect worker shutdown admission rather than a request timeout.',
        unavailable: 'Is the production worker pool shutting down at this moment?' },
    { id: 'worker-slot-release', split: 'train', domain: 'training', path: 'persistence/api/src/chat/workers.ts', topic: 'worker lane release after termination',
        anchor: '// Keep the lane occupied until the OS confirms termination.', question: 'Until when does the worker keep an execution lane occupied?',
        followup: 'What must confirm termination before that lane is released?', correction: 'I meant releasing a worker lane rather than merely sending a kill signal.',
        unavailable: 'One operator says a timed-out worker exited and another says it remains alive; what is its actual state?' },
    { id: 'worker-queue-bound', split: 'train', domain: 'persistence', path: 'persistence/api/src/chat/workers.ts', topic: 'worker queue admission',
        anchor: "if (this.queued.length >= 16) return Promise.reject(new ChatWorkerError('chat worker queue is full', 429));",
        question: 'What queue length causes worker admission to return the queue-full error?', followup: 'Which limit and HTTP status appear in that admission guard?',
        correction: 'Check queued worker tasks, rather than the number of transcript messages.',
        unavailable: 'How many worker tasks are queued on the production server right now?' },
    { id: 'worker-heap', split: 'train', domain: 'persistence', path: 'persistence/api/src/chat/workers.ts', topic: 'the child worker JavaScript heap',
        anchor: "execArgv: ['--max-old-space-size=512']", question: 'Which Node heap argument is supplied when the worker process is forked?',
        followup: 'What old-space setting does that fork call pass?', correction: 'I mean the JavaScript heap flag, not total native process memory.',
        unavailable: 'What is the current resident memory of the production training process?' },
    { id: 'memory-no-live-weights', split: 'train', domain: 'evidence', path: 'persistence/api/src/chat/memory.ts', topic: 'memory and live model weights',
        anchor: 'No live weights or public cache are mutated.',
        question: 'What does the memory service comment say about live weights and the public cache?', followup: 'Does admitting those records update live model weights?',
        correction: 'I meant memory admission rather than offline neural training.',
        unavailable: 'Which private conversations were included in an externally trained checkpoint?' },
    { id: 'memory-record-bound', split: 'train', domain: 'persistence', path: 'persistence/api/src/chat/memory.ts', topic: 'the memory record bound',
        anchor: "if (next.records.length > 1000) throw new ChatServiceError('memory record limit reached', 413);",
        question: 'Which memory record count triggers the configured limit error?', followup: 'What count and HTTP status does that memory guard use?',
        correction: 'Look at saved memory records rather than a model vocabulary limit.',
        unavailable: 'How many memory records does a different owner currently have?' },
    { id: 'memory-owner-check', split: 'train', domain: 'persistence', path: 'persistence/api/src/chat/memory.ts', topic: 'memory owner validation',
        anchor: "if (document.ownerId !== this.ownerId) throw new ChatServiceError('memory owner mismatch', 500);",
        question: 'Which guard rejects a memory document belonging to another owner?', followup: 'What mismatch does that read-time check reject?',
        correction: 'I mean the stored document owner check, rather than a conversation ID check.',
        unavailable: 'Did an actual memory owner mismatch occur on the production server yesterday?' },
    { id: 'retrieval-defaults', split: 'train', domain: 'evidence', path: 'persistence/api/src/knowledge/retrieval.ts', topic: 'lexical retrieval defaults',
        anchor: 'pathWeight: 2, minimumCoverage: 0.5, defaultLimit: 5,', question: 'Which default path weight, coverage and hit limit are declared for lexical retrieval?',
        followup: 'What are those three configured retrieval values?', correction: 'Inspect the standalone retrieval defaults rather than the repository-specific overrides.',
        unavailable: 'What recall did the retrieval system measure on our private production queries?' },
    { id: 'retrieval-not-training', split: 'train', domain: 'evidence', path: 'persistence/api/src/knowledge/retrieval.ts', topic: 'the lexical retrieval baseline',
        anchor: 'Both snapshot splits are searchable; this does not train a model.',
        question: 'Does searching the snapshot splits train a model in the BM25 baseline?', followup: 'What distinction does that retrieval comment make about training?',
        correction: 'I meant lexical indexing rather than updating neural model parameters.',
        unavailable: 'One operator reports eighty percent retrieval recall and another reports ninety; which figure is verified?' },
    { id: 'citation-coordinates', split: 'train', domain: 'evidence', path: 'persistence/api/src/knowledge/retrieval.ts', topic: 'repository citation coordinates',
        anchor: '// These coordinates refer to normalized JSONL text, NOT raw Git blob line numbers.',
        question: 'What text coordinate system do repository citation lines refer to?', followup: 'Are those coordinates raw Git blob line numbers?',
        correction: 'Check the citation coordinate comment instead of assuming checkout line numbers.',
        unavailable: 'Which current uncommitted checkout line corresponds to a citation from an unknown snapshot?' },
    { id: 'token-list-reset', split: 'train', domain: 'native', path: 'src/core/tokenizer.c', topic: 'token list cleanup',
        anchor: '* @brief Free all token spellings and reset their owning list.', question: 'What does token list destruction release and reset?',
        followup: 'Which ownership cleanup does that function document?', correction: 'I mean token-list destruction rather than destroying an entire neural model.',
        unavailable: 'How many bytes did the last token-list cleanup free in production?' },
    { id: 'token-pointer-array', split: 'train', domain: 'native', path: 'src/core/tokenizer.c', topic: 'token string and pointer allocation',
        anchor: '/* The pointer array is separate from the strings it references. */', question: 'How does tokenizer cleanup describe the pointer array relative to token strings?',
        followup: 'Is that pointer array the same allocation as its strings?', correction: 'Inspect allocation ownership rather than the spelling of a token.',
        unavailable: 'Did our production tokenizer leak a pointer array during its most recent request?' },
    { id: 'token-case-folding', split: 'train', domain: 'native', path: 'src/core/tokenizer.c', topic: 'tokenizer case normalization',
        anchor: '* Normalization follows the process C locale; this is not full Unicode case folding.',
        question: 'Does tokenizer normalization provide full Unicode case folding?', followup: 'Which locale rule governs that normalization?',
        correction: 'I meant the implemented case-folding behavior, rather than Unicode normalization in a client.',
        unavailable: 'Which locale is the production process currently running under?' },
    { id: 'chat-shape-initializer', split: 'train', domain: 'training', path: 'src/chat/chat_model.c', topic: 'the native chat default configuration initializer',
        anchor: 'const cgai_chat_config config = {8U, 16U, 16U, 160U, 32U, 42U, 1.0, 0U};',
        question: 'What initializer does cgai_chat_default_config return?', followup: 'Which complete initializer defines that reproducible default shape?',
        correction: 'Use the chat configuration initializer rather than standalone neural defaults.',
        unavailable: 'One operator says production uses defaults and another says a custom shape; which configuration is deployed?' },
    { id: 'training-spellings', split: 'train', domain: 'training', path: 'src/chat/chat_model.c', topic: 'the chat training vocabulary corpus',
        anchor: '/** @brief Collect only training spellings, independently from structural controls.',
        question: 'Which spellings does the chat training corpus collector gather?', followup: 'Does that collector mix ordinary training spellings with structural controls?',
        correction: 'I mean the vocabulary corpus collector rather than generated answer tokens.',
        unavailable: 'What exact vocabulary coverage will the model achieve on a new unseen repository?' },

    { id: 'neural-owned-handle', split: 'development', domain: 'native', path: 'include/centroid_gai_neural.h', topic: 'standalone neural model ownership',
        anchor: '/** Owned opaque neural model; release with cgai_neural_destroy(). */', question: 'Which function releases the owned opaque standalone neural model?',
        followup: 'How must that owned model handle be released?', correction: 'I mean destruction of the standalone neural handle, not a token list.',
        unavailable: 'How many standalone neural handles are currently leaked in production?' },
    { id: 'adam-call-state', split: 'development', domain: 'training', path: 'include/centroid_gai_neural.h', topic: 'Adam state between training calls',
        anchor: '/** Adam settings; continuation calls retain optimizer state in the model. */', question: 'What happens to optimizer state across standalone neural continuation calls?',
        followup: 'Is Adam state retained across those continuation calls?', correction: 'Check optimizer state across continuation calls rather than across examples within one call.',
        unavailable: 'One training operator claims Adam moments were restored and another denies it; what happened in that external run?' },
    { id: 'neural-context-bound', split: 'development', domain: 'native', path: 'include/centroid_gai_neural.h', topic: 'the standalone neural context window',
        anchor: 'size_t context_window;       /**< Ordered preceding tokens, 1..256. */', question: 'Which range does the public neural header document for the context window?',
        followup: 'What lower and upper bounds apply to that token window?', correction: 'I meant the standalone context_window field, not the chat evidence window.',
        unavailable: 'What context length did a remote user configure for their model?' },
    { id: 'neural-token-accuracy', split: 'development', domain: 'training', path: 'include/centroid_gai_neural.h', topic: 'teacher-forced token accuracy',
        anchor: 'double accuracy;       /**< Fraction of targets selected by greedy prediction. */', question: 'How does the neural metric structure define accuracy?',
        followup: 'What fraction does that accuracy field measure?', correction: 'I mean token prediction accuracy rather than factual claim support.',
        unavailable: 'What factual correctness rate does that token accuracy imply for our chatbot?' },
    { id: 'grounding-legacy', split: 'development', domain: 'evidence', path: 'persistence/api/src/chat/grounding.ts', topic: 'legacy model evidence admission',
        anchor: "if (metadata.protocolVersion < 2) return { entries: [], messages: [], reason: 'legacy model requires retraining for evidence protocol two' };",
        question: 'What does evidence selection do for a model with protocolVersion below two?', followup: 'Which legacy protocol guard prevents admitting evidence there?',
        correction: 'I meant evidence selection for legacy models, not whether their artifact can be loaded.',
        unavailable: 'Has every deployed legacy model already been retrained for evidence protocol two?' },
    { id: 'grounding-admission-heuristic', split: 'development', domain: 'evidence', path: 'persistence/api/src/chat/grounding.ts', topic: 'lexical evidence admission',
        anchor: '/** Rank complete source sentences/lines; lexical relevance is only an admission heuristic. */',
        question: 'What limitation does the evidence selector document about lexical relevance?', followup: 'Is that lexical relevance score a semantic truth guarantee?',
        correction: 'I mean source admission relevance rather than independent verification of source truth.',
        unavailable: 'What calibrated probability of factual truth corresponds to a lexical match score of three?' },
    { id: 'grounding-unit-count', split: 'development', domain: 'evidence', path: 'persistence/api/src/chat/grounding.ts', topic: 'the number of admitted evidence units',
        anchor: 'if (entries.length === 3) break;', question: 'Which source line stops evidence selection after three admitted entries?',
        followup: 'At what entry count does that selection loop stop?', correction: 'Check the admitted unit count rather than the number of fetched pages.',
        unavailable: 'Which three passages were admitted in a production request whose trace was not captured?' },
    { id: 'local-store-lock', split: 'development', domain: 'persistence', path: 'persistence/api/src/chat/file-store.ts', topic: 'local chat store ownership',
        anchor: 'The lock forbids two API processes sharing one file.',
        question: 'What does the local file store lock prohibit?', followup: 'Can two API processes share that locked store file?',
        correction: 'I mean local file-store locking rather than PostgreSQL replication.',
        unavailable: 'Which operating-system process currently owns an inaccessible production store lock?' },
    { id: 'memory-revision-check', split: 'development', domain: 'persistence', path: 'persistence/api/src/chat/file-store.ts', topic: 'file-store memory revision changes',
        anchor: "if (value.revision !== expectedRevision + 1) throw new Error('memory revision must advance by one');",
        question: 'What revision increment does the file store require when saving memory?', followup: 'How far must that memory revision advance?',
        correction: 'Inspect memory revision increments rather than transcript sequence numbers.',
        unavailable: 'Which revision is currently stored for a private production owner?' },
    { id: 'clang-format-command', split: 'development', domain: 'build', path: 'cmake/Lint.cmake', topic: 'format-check execution',
        anchor: 'COMMAND "${CLANG_FORMAT_EXECUTABLE}" --dry-run --Werror ${CGAI_FORMAT_SOURCES}',
        question: 'Which clang-format flags does the CMake format-check target execute?', followup: 'How does that target make formatting problems fail the check?',
        correction: 'I meant the format-check command rather than an in-place formatting command.',
        unavailable: 'Did the formatting target pass on the newest uncommitted source changes?' },

    { id: 'quality-byte-bound', split: 'test', domain: 'training', path: 'persistence/api/src/chat/training-quality.ts', topic: 'the development validation byte limit',
        anchor: "if (Buffer.byteLength(JSON.stringify(value)) > 1024 * 1024) throw new Error('validation suite exceeds 1 MiB');",
        question: 'Which guard limits the serialized development validation suite to one MiB?', followup: 'What serialized byte bound does that suite guard enforce?',
        correction: 'I meant development validation bytes rather than native artifact bytes.',
        unavailable: 'What size will a future validation suite uploaded by another team have?' },
    { id: 'quality-coverage', split: 'test', domain: 'training', path: 'persistence/api/src/chat/training-quality.ts', topic: 'answerable and unanswerable validation coverage',
        anchor: "if (!answerable || !unanswerable) throw new Error('validation requires answerable and unanswerable coverage');",
        question: 'Which guard requires both answerable and unanswerable development examples?', followup: 'Which two kinds of coverage are mandatory there?',
        correction: 'Check answerability coverage rather than whether every example has a citation.',
        unavailable: 'Does covering both answerability classes prove the model is production-ready?' },
    { id: 'quality-exact-not-semantic', split: 'test', domain: 'training', path: 'persistence/api/src/chat/training-quality.ts', topic: 'the quality checker claim scope',
        anchor: 'No lexical-overlap or model-judged semantic claims.',
        question: 'How does the quality module describe the limits of its deterministic checks?', followup: 'Do those checks claim model-judged semantic verification?',
        correction: 'I mean what the extractive checker actually verifies rather than a future semantic judge.',
        unavailable: 'Which disputed scientific claim is true merely because a model repeated an exact quotation?' },
    { id: 'research-deadline', split: 'test', domain: 'evidence', path: 'persistence/api/src/chat/research.ts', topic: 'the public research deadline',
        anchor: 'const bounded = AbortSignal.any([signal, AbortSignal.timeout(15000)]);', question: 'Which code sets the bounded public research timeout?',
        followup: 'What millisecond timeout is combined with the caller signal?', correction: 'I meant the research deadline, not a native inference deadline.',
        unavailable: 'How long did an uncaptured public research request actually take yesterday?' },
    { id: 'research-page-attempts', split: 'test', domain: 'evidence', path: 'persistence/api/src/chat/research.ts', topic: 'bounded public page attempts',
        anchor: 'for (const hit of hits.slice(0, 5)) {', question: 'Which loop limits public research to the first five search hits?',
        followup: 'How many initial search hits can that fetch loop inspect?', correction: 'I meant page attempts rather than the number of admitted neural evidence units.',
        unavailable: 'Which public pages did a missing research trace actually fetch?' },
    { id: 'research-query-bytes', split: 'test', domain: 'evidence', path: 'persistence/api/src/chat/research.ts', topic: 'public query validation',
        anchor: "chatText(query, 'publicQuery', 512);", question: 'Which call bounds the public search query to 512 UTF-8 bytes?',
        followup: 'What byte limit does that publicQuery validation call pass?', correction: 'Check public query bytes rather than total conversation retention.',
        unavailable: 'What private text did an unknown external search client submit last week?' },
    { id: 'candidate-before-head', split: 'test', domain: 'persistence', path: 'persistence/api/src/chat/store.ts', topic: 'candidate artifacts and model heads',
        anchor: '/** Persist an immutable candidate without changing any named model head. */',
        question: 'What does the saveArtifact contract promise about named model heads?', followup: 'Does storing that candidate itself replace a published head?',
        correction: 'I mean saving an immutable candidate rather than publishing it.',
        unavailable: 'One operator reports candidate approval and another reports rejection; which model is currently published?' },
    { id: 'chat-message-limit', split: 'test', domain: 'native', path: 'src/chat/chat_prompt.c', topic: 'the native chat message-count guard',
        anchor: 'return cgai_fail("chat requires 1..1024 messages");', question: 'What message-count range does the native chat formatter report as required?',
        followup: 'Which allowed count range appears in that failure diagnostic?', correction: 'I meant structured message count rather than token count.',
        unavailable: 'How many structured messages are in a private remote conversation right now?' },
    { id: 'chat-alternating-turns', split: 'test', domain: 'native', path: 'src/chat/chat_prompt.c', topic: 'native chat dialogue ordering',
        anchor: 'return cgai_fail("chat history must contain complete alternating turns");', question: 'What does the native validator require about chat history turn ordering?',
        followup: 'Which complete-turn requirement does that diagnostic describe?', correction: 'I meant dialogue role ordering rather than source rank ordering.',
        unavailable: 'Did an inaccessible client submit a malformed conversation to production?' },
    { id: 'chat-current-question', split: 'test', domain: 'native', path: 'src/chat/chat_prompt.c', topic: 'the final native chat message',
        anchor: 'cgai_fail("chat history must end with the current user question");', question: 'Which diagnostic states how native chat history must end?',
        followup: 'What role and purpose must the final message have?', correction: 'Inspect the final current-question rule rather than the role of older evidence.',
        unavailable: 'What was the exact last private user question in an uncaptured conversation?' },
];
