# Local SDK archives. CPack generation does not publish or qualify a release.
set(CPACK_PACKAGE_NAME Centroid)
set(CPACK_PACKAGE_VENDOR "Centroid contributors")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Local strict C11 centroid inference SDK")
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _centroid_package_architecture)
if(_centroid_package_architecture MATCHES "^(amd64|x86_64|x86-64)$")
  set(_centroid_package_architecture x86_64)
endif()
if(CENTROID_BUILD_TRAINING OR CENTROID_BUILD_TOOLS)
  set(_centroid_package_flavor sdk)
else()
  set(_centroid_package_flavor runtimeonly)
endif()
if(BUILD_SHARED_LIBS)
  set(_centroid_package_linkage runtime-shared)
else()
  set(_centroid_package_linkage runtime-static)
endif()
set(CPACK_PACKAGE_FILE_NAME
  "centroid-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${_centroid_package_architecture}-${_centroid_package_flavor}-${_centroid_package_linkage}")
# A workspace source sweep would include ignored/private research artifacts.
# Source releases need a separately reviewed input manifest, not CPack defaults.
set(CPACK_SOURCE_GENERATOR "")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "")
if(WIN32)
  set(CPACK_GENERATOR ZIP)
else()
  set(CPACK_GENERATOR TGZ)
endif()
set(CPACK_COMPONENTS_ALL Runtime)
if(CENTROID_BUILD_TRAINING)
  list(APPEND CPACK_COMPONENTS_ALL Training)
endif()
if(CENTROID_BUILD_TOOLS)
  list(APPEND CPACK_COMPONENTS_ALL Tools)
endif()
if(CENTROID_BUILD_EXAMPLES)
  list(APPEND CPACK_COMPONENTS_ALL Examples)
endif()
set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Inference runtime")
set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "Immutable model loading, prediction and bounded context; no trainer or tool launcher")
set(CPACK_COMPONENT_TRAINING_DISPLAY_NAME "Legacy training and workflow library")
set(CPACK_COMPONENT_TRAINING_DESCRIPTION "Optional compatibility library containing Life training, capture and research workflows")
set(CPACK_COMPONENT_TRAINING_DEPENDS Runtime)
set(CPACK_COMPONENT_TOOLS_DISPLAY_NAME "Native development tools")
set(CPACK_COMPONENT_TOOLS_DESCRIPTION "Explicit training, qualification, capture and evaluation commands")
set(CPACK_COMPONENT_TOOLS_DEPENDS Runtime Training)
set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Native host example")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Provider-free code-context application and standalone CMake consumer source")
set(CPACK_COMPONENT_EXAMPLES_DEPENDS Runtime)
# Archive installation contains configured components in one relocatable tree.
set(CPACK_ARCHIVE_COMPONENT_INSTALL OFF)
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
  foreach(_centroid_licensed_component IN LISTS CPACK_COMPONENTS_ALL)
    install(FILES LICENSE DESTINATION ${CMAKE_INSTALL_DATADIR}/doc/Centroid
      COMPONENT ${_centroid_licensed_component})
  endforeach()
endif()
foreach(_centroid_document SDK BUNDLE_FORMAT)
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/docs/${_centroid_document}.md")
    install(FILES "docs/${_centroid_document}.md"
      DESTINATION ${CMAKE_INSTALL_DATADIR}/doc/Centroid COMPONENT Runtime)
  endif()
endforeach()
include(CPack)
