# Invoked by NeuralModel.cmake targets or directly with cmake -D... -P.
foreach(required IN ITEMS CGAI_EXE CGAI_MODEL_DIR CGAI_MODEL_BUILD_DIR CGAI_MODEL_ACTION)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
if(NOT EXISTS "${CGAI_EXE}")
    message(FATAL_ERROR "CGAI_EXE does not exist: ${CGAI_EXE}")
endif()
if(NOT CGAI_MODEL_ACTION MATCHES "^(validate|verify|step|reproduce)$")
    message(FATAL_ERROR "Unknown neural model action: ${CGAI_MODEL_ACTION}")
endif()
if(NOT EXISTS "${CGAI_MODEL_DIR}/recipe.cmake")
    message(FATAL_ERROR "Missing neural model recipe: ${CGAI_MODEL_DIR}/recipe.cmake")
endif()

include("${CGAI_MODEL_DIR}/recipe.cmake")
foreach(required IN ITEMS CGAI_MODEL_EPOCHS CGAI_MODEL_RATE CGAI_MODEL_TRAIN_SHA256
        CGAI_MODEL_HELDOUT_SHA256 CGAI_MODEL_CHECKPOINT_SHA256 CGAI_MODEL_METRICS_SHA256)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Neural model recipe requires ${required}")
    endif()
endforeach()
if(NOT CGAI_MODEL_EPOCHS MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "CGAI_MODEL_EPOCHS must be a positive integer")
endif()
string(LENGTH "${CGAI_MODEL_EPOCHS}" cgai_epochs_length)
if(cgai_epochs_length GREATER 5 OR CGAI_MODEL_EPOCHS GREATER 10000)
    message(FATAL_ERROR "CGAI_MODEL_EPOCHS must be in the supported range 1..10000")
endif()
if(NOT CGAI_MODEL_RATE MATCHES "^[0-9]+([.][0-9]+)?([eE][-+]?[0-9]+)?$"
        OR CGAI_MODEL_RATE MATCHES "^0+([.]0+)?([eE][-+]?[0-9]+)?$")
    message(FATAL_ERROR "CGAI_MODEL_RATE must be a positive finite learning rate")
endif()

function(cgai_model_require_hash path expected)
    string(LENGTH "${expected}" expected_length)
    if(NOT expected_length EQUAL 64 OR NOT expected MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "Invalid recipe SHA256 for ${path}")
    endif()
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "Missing neural model artifact: ${path}")
    endif()
    file(SHA256 "${path}" actual)
    string(TOLOWER "${expected}" normalized)
    if(NOT actual STREQUAL normalized)
        message(FATAL_ERROR
            "Neural model SHA256 mismatch for ${path}: expected ${normalized}, got ${actual}")
    endif()
endfunction()

function(cgai_model_run report)
    message(STATUS "Running cgai ${ARGN}")
    execute_process(COMMAND "${CGAI_EXE}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT "${output}" STREQUAL "")
        message("${output}")
    endif()
    if(NOT "${error}" STREQUAL "")
        message("${error}")
    endif()
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "cgai ${ARGN} failed with status ${status}")
    endif()
    if(NOT "${report}" STREQUAL "")
        file(WRITE "${report}" "${output}")
    endif()
endfunction()

set(cgai_train "${CGAI_MODEL_DIR}/train.txt")
set(cgai_heldout "${CGAI_MODEL_DIR}/heldout.txt")
set(cgai_checkpoint "${CGAI_MODEL_DIR}/checkpoint.txt")
cgai_model_require_hash("${cgai_train}" "${CGAI_MODEL_TRAIN_SHA256}")
cgai_model_require_hash("${cgai_heldout}" "${CGAI_MODEL_HELDOUT_SHA256}")
cgai_model_require_hash("${cgai_checkpoint}" "${CGAI_MODEL_CHECKPOINT_SHA256}")
cgai_model_require_hash("${CGAI_MODEL_DIR}/metrics.tsv" "${CGAI_MODEL_METRICS_SHA256}")

# Source artifacts cannot be destinations, even in a direct script invocation.
get_filename_component(cgai_source_dir "${CGAI_MODEL_DIR}" REALPATH)
get_filename_component(cgai_build_dir "${CGAI_MODEL_BUILD_DIR}" ABSOLUTE)
cmake_path(IS_PREFIX cgai_source_dir "${cgai_build_dir}" NORMALIZE cgai_in_source)
if(cgai_in_source)
    message(FATAL_ERROR "CGAI_MODEL_BUILD_DIR must be outside the tracked model directory")
endif()
file(MAKE_DIRECTORY "${cgai_build_dir}")

if(CGAI_MODEL_ACTION STREQUAL "validate")
    cgai_model_run("" neural-export "${cgai_checkpoint}" "${cgai_build_dir}/validated.cgnn")
    cgai_model_run("${cgai_build_dir}/validated.metrics.tsv" neural-evaluate
        "${cgai_build_dir}/validated.cgnn" "${cgai_heldout}")
    message(STATUS "Tracked model hashes, checkpoint loading, and held-out evaluation passed")
elseif(CGAI_MODEL_ACTION STREQUAL "verify")
    set(cgai_result "${cgai_build_dir}/replayed.txt")
    cgai_model_run("" neural-replay "${cgai_checkpoint}" "${cgai_train}"
        "${cgai_result}" "${CGAI_MODEL_RATE}")
    cgai_model_require_hash("${cgai_result}" "${CGAI_MODEL_CHECKPOINT_SHA256}")
    message(STATUS "Tracked model replay is byte-identical: ${cgai_result}")
elseif(CGAI_MODEL_ACTION STREQUAL "step")
    if(NOT DEFINED CGAI_MODEL_STEP_EPOCHS)
        set(CGAI_MODEL_STEP_EPOCHS 1)
    endif()
    if(NOT DEFINED CGAI_MODEL_STEP_RATE)
        set(CGAI_MODEL_STEP_RATE 0.015)
    endif()
    cgai_model_run("${cgai_build_dir}/candidate.metrics.tsv" neural-step
        "${cgai_checkpoint}" "${cgai_train}" "${cgai_heldout}"
        "${cgai_build_dir}/candidate.txt" "${CGAI_MODEL_STEP_EPOCHS}" "${CGAI_MODEL_STEP_RATE}")
    message(STATUS "Improved model proposal: ${cgai_build_dir}/candidate.txt")
    message(STATUS "Proposal report: ${cgai_build_dir}/candidate.metrics.tsv")
elseif(CGAI_MODEL_ACTION STREQUAL "reproduce")
    set(cgai_initial "${cgai_build_dir}/reproduce-initial.txt")
    set(cgai_result "${cgai_build_dir}/reproduced.txt")
    cgai_model_run("" neural-init "${cgai_train}" "${cgai_initial}")
    cgai_model_run("${cgai_build_dir}/reproduced.metrics.tsv" neural-step
        "${cgai_initial}" "${cgai_train}" "${cgai_heldout}" "${cgai_result}"
        "${CGAI_MODEL_EPOCHS}" "${CGAI_MODEL_RATE}")
    cgai_model_require_hash("${cgai_result}" "${CGAI_MODEL_CHECKPOINT_SHA256}")
    message(STATUS "Tracked model reproduced byte-identically: ${cgai_result}")
endif()
